const gfg = (q) => `https://www.geeksforgeeks.org/?s=${encodeURIComponent(q)}`;
const lc = (slug) => `https://leetcode.com/problems/${slug}/`;

export const BASE_TOPICS = [
  { name:"Arrays", items:[
    ["Two Sum","Easy","LeetCode",lc("two-sum")],
    ["Best Time to Buy and Sell Stock","Easy","LeetCode",lc("best-time-to-buy-and-sell-stock")],
    ["Leaders in an Array","Easy","GFG",gfg("Leaders in an array")],
    ["Maximum Subarray (Kadane's)","Medium","LeetCode",lc("maximum-subarray")],
    ["Merge Intervals","Medium","LeetCode",lc("merge-intervals")],
    ["Rotate Array","Medium","LeetCode",lc("rotate-array")],
    ["Product of Array Except Self","Medium","LeetCode",lc("product-of-array-except-self")],
    ["Trapping Rain Water","Hard","LeetCode",lc("trapping-rain-water")],
  ]},
  { name:"Strings", items:[
    ["Valid Palindrome","Easy","LeetCode",lc("valid-palindrome")],
    ["Reverse Words in a String","Medium","LeetCode",lc("reverse-words-in-a-string")],
    ["Longest Common Prefix","Easy","LeetCode",lc("longest-common-prefix")],
    ["Valid Anagram","Easy","LeetCode",lc("valid-anagram")],
    ["Group Anagrams","Medium","LeetCode",lc("group-anagrams")],
    ["Longest Substring Without Repeating Characters","Medium","LeetCode",lc("longest-substring-without-repeating-characters")],
    ["String to Integer (atoi)","Medium","LeetCode",lc("string-to-integer-atoi")],
    ["Count and Say","Medium","LeetCode",lc("count-and-say")],
  ]},
  { name:"Hashing", items:[
    ["Two Sum (Hash Map)","Easy","LeetCode",lc("two-sum")],
    ["Contains Duplicate","Easy","LeetCode",lc("contains-duplicate")],
    ["Longest Consecutive Sequence","Medium","LeetCode",lc("longest-consecutive-sequence")],
    ["Subarray Sum Equals K","Medium","LeetCode",lc("subarray-sum-equals-k")],
    ["Top K Frequent Elements","Medium","LeetCode",lc("top-k-frequent-elements")],
    ["Valid Sudoku","Medium","LeetCode",lc("valid-sudoku")],
    ["First Missing Positive","Hard","LeetCode",lc("first-missing-positive")],
    ["Count Distinct Elements in Window","Easy","GFG",gfg("Count distinct elements in every window")],
  ]},
  { name:"Sorting", items:[
    ["Sort Colors (Dutch National Flag)","Medium","LeetCode",lc("sort-colors")],
    ["Merge Sorted Array","Easy","LeetCode",lc("merge-sorted-array")],
    ["Kth Largest Element","Medium","LeetCode",lc("kth-largest-element-in-an-array")],
    ["Sort an Array","Medium","LeetCode",lc("sort-an-array")],
    ["Majority Element","Easy","LeetCode",lc("majority-element")],
    ["Move Zeroes","Easy","LeetCode",lc("move-zeroes")],
    ["Largest Number","Medium","LeetCode",lc("largest-number")],
    ["Find Minimum in Rotated Sorted Array","Medium","LeetCode",lc("find-minimum-in-rotated-sorted-array")],
  ]},
  { name:"Binary Search", items:[
    ["Binary Search","Easy","LeetCode",lc("binary-search")],
    ["Search in Rotated Sorted Array","Medium","LeetCode",lc("search-in-rotated-sorted-array")],
    ["Find First and Last Position","Medium","LeetCode",lc("find-first-and-last-position-of-element-in-sorted-array")],
    ["Search Insert Position","Easy","LeetCode",lc("search-insert-position")],
    ["Square Root (Binary Search)","Easy","LeetCode",lc("sqrtx")],
    ["Koko Eating Bananas","Medium","LeetCode",lc("koko-eating-bananas")],
    ["Median of Two Sorted Arrays","Hard","LeetCode",lc("median-of-two-sorted-arrays")],
    ["Aggressive Cows","Medium","GFG",gfg("Aggressive Cows")],
  ]},
  { name:"Linked List", items:[
    ["Reverse a Linked List","Easy","LeetCode",lc("reverse-linked-list")],
    ["Middle of Linked List","Easy","LeetCode",lc("middle-of-the-linked-list")],
    ["Merge Two Sorted Lists","Easy","LeetCode",lc("merge-two-sorted-lists")],
    ["Remove Nth Node From End","Medium","LeetCode",lc("remove-nth-node-from-end-of-list")],
    ["Detect Cycle in Linked List","Easy","LeetCode",lc("linked-list-cycle")],
    ["Palindrome Linked List","Easy","LeetCode",lc("palindrome-linked-list")],
    ["Intersection of Two Linked Lists","Easy","LeetCode",lc("intersection-of-two-linked-lists")],
    ["Reverse Nodes in k-Group","Hard","LeetCode",lc("reverse-nodes-in-k-group")],
  ]},
  { name:"Stack", items:[
    ["Valid Parentheses","Easy","LeetCode",lc("valid-parentheses")],
    ["Min Stack","Medium","LeetCode",lc("min-stack")],
    ["Evaluate Reverse Polish Notation","Medium","LeetCode",lc("evaluate-reverse-polish-notation")],
    ["Next Greater Element","Easy","LeetCode",lc("next-greater-element-i")],
    ["Daily Temperatures","Medium","LeetCode",lc("daily-temperatures")],
    ["Largest Rectangle in Histogram","Hard","LeetCode",lc("largest-rectangle-in-histogram")],
    ["Implement Queue Using Stacks","Easy","LeetCode",lc("implement-queue-using-stacks")],
    ["Decode String","Medium","LeetCode",lc("decode-string")],
  ]},
  { name:"Queue", items:[
    ["Implement Stack Using Queues","Easy","LeetCode",lc("implement-stack-using-queues")],
    ["Sliding Window Maximum","Hard","LeetCode",lc("sliding-window-maximum")],
    ["Number of Recent Calls","Easy","LeetCode",lc("number-of-recent-calls")],
    ["Reverse First K Elements of Queue","Medium","GFG",gfg("Reverse First K elements of Queue")],
    ["Circular Tour (Petrol Pump)","Medium","GFG",gfg("Circular tour petrol pump")],
    ["First Non-Repeating Character in Stream","Medium","GFG",gfg("First non repeating character in a stream")],
    ["Interleaving Two Queues","Medium","GFG",gfg("Interleave the first half of the queue with second half")],
    ["Implement Deque","Medium","GFG",gfg("Implement Deque using doubly linked list")],
  ]},
  { name:"Trees", items:[
    ["Maximum Depth of Binary Tree","Easy","LeetCode",lc("maximum-depth-of-binary-tree")],
    ["Invert Binary Tree","Easy","LeetCode",lc("invert-binary-tree")],
    ["Same Tree","Easy","LeetCode",lc("same-tree")],
    ["Binary Tree Level Order Traversal","Medium","LeetCode",lc("binary-tree-level-order-traversal")],
    ["Validate Binary Search Tree","Medium","LeetCode",lc("validate-binary-search-tree")],
    ["Lowest Common Ancestor of BT","Medium","LeetCode",lc("lowest-common-ancestor-of-a-binary-tree")],
    ["Binary Tree Right Side View","Medium","LeetCode",lc("binary-tree-right-side-view")],
    ["Binary Tree Zigzag Level Order","Medium","LeetCode",lc("binary-tree-zigzag-level-order-traversal")],
  ]},
  { name:"BST", items:[
    ["Search in a BST","Easy","LeetCode",lc("search-in-a-binary-search-tree")],
    ["Insert into a BST","Medium","LeetCode",lc("insert-into-a-binary-search-tree")],
    ["Delete a Node in BST","Medium","LeetCode",lc("delete-node-in-a-bst")],
    ["Convert Sorted Array to BST","Easy","LeetCode",lc("convert-sorted-array-to-binary-search-tree")],
    ["Kth Smallest Element in BST","Medium","LeetCode",lc("kth-smallest-element-in-a-bst")],
    ["Validate BST","Medium","LeetCode",lc("validate-binary-search-tree")],
    ["Lowest Common Ancestor of BST","Medium","LeetCode",lc("lowest-common-ancestor-of-a-binary-search-tree")],
    ["BST Iterator","Medium","LeetCode",lc("binary-search-tree-iterator")],
  ]},
  { name:"Heap", items:[
    ["Kth Largest Element in Array","Medium","LeetCode",lc("kth-largest-element-in-an-array")],
    ["Top K Frequent Elements","Medium","LeetCode",lc("top-k-frequent-elements")],
    ["Merge K Sorted Lists","Hard","LeetCode",lc("merge-k-sorted-lists")],
    ["Find Median from Data Stream","Hard","LeetCode",lc("find-median-from-data-stream")],
    ["Last Stone Weight","Easy","LeetCode",lc("last-stone-weight")],
    ["K Closest Points to Origin","Medium","LeetCode",lc("k-closest-points-to-origin")],
    ["Task Scheduler","Medium","LeetCode",lc("task-scheduler")],
    ["Connect Rope with Minimum Cost","Easy","GFG",gfg("Minimum Cost of ropes")],
  ]},
  { name:"Sliding Window", items:[
    ["Maximum Sum Subarray of Size K","Easy","GFG",gfg("Maximum Sum Subarray of Size K")],
    ["Longest Substring Without Repeating","Medium","LeetCode",lc("longest-substring-without-repeating-characters")],
    ["Minimum Window Substring","Hard","LeetCode",lc("minimum-window-substring")],
    ["Sliding Window Maximum","Hard","LeetCode",lc("sliding-window-maximum")],
    ["Longest Repeating Character Replacement","Medium","LeetCode",lc("longest-repeating-character-replacement")],
    ["Permutation in String","Medium","LeetCode",lc("permutation-in-string")],
    ["Fruit Into Baskets","Medium","LeetCode",lc("fruit-into-baskets")],
    ["Count Number of Nice Subarrays","Medium","LeetCode",lc("count-number-of-nice-subarrays")],
  ]},
  { name:"Greedy", items:[
    ["Assign Cookies","Easy","LeetCode",lc("assign-cookies")],
    ["Jump Game","Medium","LeetCode",lc("jump-game")],
    ["Jump Game II","Medium","LeetCode",lc("jump-game-ii")],
    ["Gas Station","Medium","LeetCode",lc("gas-station")],
    ["Activity Selection / N Meetings","Easy","GFG",gfg("N meeting in one room")],
    ["Fractional Knapsack","Medium","GFG",gfg("Fractional Knapsack")],
    ["Minimum Platforms","Medium","GFG",gfg("Minimum Platforms")],
    ["Lemonade Change","Easy","LeetCode",lc("lemonade-change")],
  ]},
  { name:"Graph", items:[
    ["Number of Islands","Medium","LeetCode",lc("number-of-islands")],
    ["Clone Graph","Medium","LeetCode",lc("clone-graph")],
    ["Flood Fill","Easy","LeetCode",lc("flood-fill")],
    ["Rotting Oranges","Medium","LeetCode",lc("rotting-oranges")],
    ["Course Schedule","Medium","LeetCode",lc("course-schedule")],
    ["Word Ladder","Hard","LeetCode",lc("word-ladder")],
    ["Detect Cycle in Undirected Graph","Medium","GFG",gfg("Detect cycle in an undirected graph")],
    ["Dijkstra's Algorithm","Medium","GFG",gfg("Dijkstra's Algorithm")],
  ]},
  { name:"Backtracking", items:[
    ["Subsets","Medium","LeetCode",lc("subsets")],
    ["Permutations","Medium","LeetCode",lc("permutations")],
    ["Combination Sum","Medium","LeetCode",lc("combination-sum")],
    ["Letter Combinations of Phone Number","Medium","LeetCode",lc("letter-combinations-of-a-phone-number")],
    ["Word Search","Medium","LeetCode",lc("word-search")],
    ["N-Queens","Hard","LeetCode",lc("n-queens")],
    ["Sudoku Solver","Hard","LeetCode",lc("sudoku-solver")],
    ["Generate Parentheses","Medium","LeetCode",lc("generate-parentheses")],
  ]},
];

export const MILESTONES = [
  {pct:20, tag:"3 Topics Clear", title:"Bronze Coder 🥉", desc:"Arrays, Strings & Hashing ground mastered."},
  {pct:40, tag:"6 Topics Clear", title:"Silver Coder 🥈", desc:"Sorting & Binary Search step completed."},
  {pct:60, tag:"9 Topics Clear", title:"Gold Coder 🥇", desc:"Trees & Stacks conquered."},
  {pct:80, tag:"12 Topics Clear", title:"Diamond Coder 💎", desc:"Graph & DP scaling the heights."},
  {pct:100, tag:"All 15 Topics", title:"Interview Ready 🌸", desc:"Mastery unlocked! Good luck on placements!"},
];
